"""empty message

Revision ID: 05eda5b125fd
Revises: 5a7477aa89cd
Create Date: 2021-01-03 20:53:10.741789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05eda5b125fd'
down_revision = '5a7477aa89cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tableone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso', sa.String(length=70), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tableone')
    # ### end Alembic commands ###
