"""empty message

Revision ID: e0619b178a0b
Revises: 
Create Date: 2021-01-03 20:39:11.982106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0619b178a0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tableone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tablethree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codeValue', sa.String(length=70), nullable=False),
    sa.Column('isPrivate', sa.String(length=70), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.Column('reference', sa.String(length=70), nullable=False),
    sa.Column('revisionNumber', sa.String(length=70), nullable=False),
    sa.Column('uri', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tabletwo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_cases_critical_percentage', sa.String(length=70), nullable=False),
    sa.Column('active_cases_mild_percentage', sa.String(length=70), nullable=False),
    sa.Column('cases_with_outcome', sa.String(length=70), nullable=False),
    sa.Column('closed_cases_death_percentage', sa.String(length=70), nullable=False),
    sa.Column('closed_cases_recovered_percentage', sa.String(length=70), nullable=False),
    sa.Column('critical_condition_active_cases', sa.String(length=70), nullable=False),
    sa.Column('currently_infected', sa.String(length=70), nullable=False),
    sa.Column('death_cases', sa.String(length=70), nullable=False),
    sa.Column('death_closed_cases', sa.String(length=70), nullable=False),
    sa.Column('general_death_rate', sa.String(length=70), nullable=False),
    sa.Column('last_update', sa.String(length=70), nullable=False),
    sa.Column('mild_condition_active_cases', sa.String(length=70), nullable=False),
    sa.Column('recovered_closed_cases', sa.String(length=70), nullable=False),
    sa.Column('recovery_cases', sa.String(length=70), nullable=False),
    sa.Column('total_cases', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabletwo')
    op.drop_table('tablethree')
    op.drop_table('tableone')
    # ### end Alembic commands ###
